### ISSUE TITLE
SublimeText2 or SublimeText3 (Windows)

### ISSUE THREAD

**Issue by craiglondon** [lgmclaughlin/AlphabetizeAttrSublime#1]
I am using Windows 8, SublimeText 2.  I got this error when trying to sort/alphabetize attributes.

`
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
    return self.run(edit)
  File ".\AlphabetizeAttr.py", line 66, in run
IndexError: string index out of range
`

**Comment by craiglondon** [comment]
Nevermind, I was selecting the attr inside the tag.  Once I selected the whole tag it sorted/alphabetized correctly!  Thank you.
